[project]
name = "tui"
version = "0.1.0"
description = "Python based terminal UI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "prompt-toolkit>=3.0.52",
    "rich>=14.2.0",
    "textual>=6.5.0",
    "textual-dev>=1.8.0",
    "types-pygments>=2.19.0.20250809",
]
